import streamlit as st
import torch
from torchvision import transforms
from PIL import Image
from model import get_model

# 1. PAGE CONFIGURATION
st.set_page_config(page_title="AI Image Detector", page_icon="🤖")

st.title("🤖 AI vs Real Image Detector")
st.write("Upload an image to see if it was generated by AI or captured by a Human.")

# 2. LOAD MODEL (Cached so it doesn't reload on every click)
@st.cache_resource
def load_trained_model():
    device = torch.device("cpu")  # Force CPU for the web app

    model = get_model()

    try:
        model.load_state_dict(torch.load("model.pt", map_location=device))
    except FileNotFoundError:
        st.error("Error: 'model.pt' not found. Please put it in the main folder.")
        return None

    model.eval()
    return model


model = load_trained_model()

# 3. IMAGE PREPROCESSING (Must match training!)
transform = transforms.Compose(
    [
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]
)

# 4. USER INTERFACE
uploaded_file = st.file_uploader(
    "Choose an image...", type=["jpg", "jpeg", "png", "webp"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_column_width=True)

    with st.spinner("Analyzing patterns..."):
        img_tensor = transform(image).unsqueeze(0)

        if model:
            with torch.no_grad():
                output = model(img_tensor)
                probabilities = torch.nn.functional.softmax(output[0], dim=0)

                # Assuming Class 0 = AI, Class 1 = Real
                ai_prob = probabilities[0].item()
                real_prob = probabilities[1].item()

            st.divider()

            if ai_prob > real_prob:
                st.error(
                    f"🚨 **FAKE / AI GENERATED** ({ai_prob*100:.1f}% Confidence)"
                )
                st.progress(ai_prob)
            else:
                st.success(
                    f"✅ **REAL / HUMAN** ({real_prob*100:.1f}% Confidence)"
                )
                st.progress(real_prob)
